name: bbl
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_tts: ^3.7.0
  vibration: ^1.7.7
  url_launcher: ^6.1.11
  external_app_launcher: ^3.1.0
  flutter_phone_direct_caller: ^2.1.1
  geolocator: ^9.0.2
  speech_to_text: ^6.1.1
  envied: ^0.3.0+3
  dart_openai: ^2.0.1
  flutter_beep: ^1.0.0
  mailer: ^6.0.1
  flutter_email_sender: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3
  build_runner: ^2.4.4

flutter:
  uses-material-design: true

flutter_phone_direct_caller: ^2.1.1
